services:
  backend:
    build: ./backend
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
  aboba:
    build: ./frontend
    ports: 
      - "5173:5173"